### ISSUE TITLE
Installing outdated version

### ISSUE THREAD

**Issue by JADSN** [open-source-labs/vno#127]
When i run `deno install -A -f --unstable https://deno.land/x/vno/install/vno.ts`always install the version `1.3.1` instead of the latest version.

![01](https://user-images.githubusercontent.com/7506354/128598199-4cbc42a6-eac6-4202-a6ef-803b401a9869.png)

**Comment by bosam** [comment]
It seems that [info.ts](https://github.com/open-source-labs/vno/blob/main/core/cli/info.ts) contains a hard coded version.
You likely are using the latest version but since that file isn't updated you'd still see it as 1.3.1.

I tried with running `deno install -A -f --unstable https://deno.land/x/vno@v1.4.5/install/vno.ts` that specifically loads the 1.4.5 version and it shows 1.3.1 due to its non-changing nature.

**Comment by adxzhang1** [comment]
Updated the cli in #128. Thanks!
